name: Build (Linux ARM64)

on: [push, pull_request]

jobs:
  build:
    runs-on: [self-hosted, linux, arm64, Raspi]
    strategy:
      matrix:
        configuration: ["Debug", "Release"]
    steps:
    - name: Install build dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config git autoconf automake libtool ccache
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Set build environment variables
      shell: bash
      run: |
        if [[ "${{ matrix.configuration }}" == "Debug" ]]; then
          echo "Configuring for Debug"
          echo "BUILD_PARAM=" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=xqemu-debug" >> $GITHUB_ENV
        else
          echo "Configuring for Release"
          echo "BUILD_PARAM=--release" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=xqemu-release" >> $GITHUB_ENV
        fi
    - name: Initialize Compiler Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: /tmp/xqemu-ccache
        key: cache-${{ runner.os }}-${{ matrix.configuration }}-${{ github.sha }}
        restore-keys: cache-${{ runner.os }}-${{ matrix.configuration }}-
    - name: Debug Environment
      shell: bash
      run: |
        echo "=== ENVIRONMENT VARIABLES ==="
        env
        echo "=== CURRENT DIRECTORY ==="
        pwd
        echo "=== DIRECTORY LISTING ==="
        ls -al $GITHUB_WORKSPACE
        echo "=== SYSTEM INFO ==="
        uname -a
    - name: Compile
      shell: bash
      run: |
        set +e
        cd "$GITHUB_WORKSPACE"
        export CCACHE_DIR=/tmp/xqemu-ccache
        export CCACHE_MAXSIZE=250M
        export PATH="/usr/lib/ccache:$PATH"
        ./build.sh ${{ env.BUILD_PARAM }}
        echo -e '\nCompiler Cache Stats:'
        ccache -s -c
        exit 0
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: dist

